### ISSUE TITLE
When creating a BMH, the image field is set, which may cause the machine to fail to choose the bmh

### ISSUE THREAD

**Issue by yanfeng1992** [metal3-io/baremetal-operator#1273]
``**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

create bmh with image url, for example

```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: demo-provisioning
  labels:
    metal3demo: ""
spec:
  online: true
  bmc:
    address: ipmi://192.168.122.6:6233
    credentialsName: demo-provisioning-secret
  bootMACAddress: 00:c6:14:04:61:b2
  userData:
    namespace: openshift-machine-api
    name: worker-user-data
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2.md5sum"
```

Because I set the image field when I created the BMH, the BMH will soon transition from the available state to the provisioning state. At this time, the cluster-api-provider-metal3 requeueAfter 30s will make it impossible to match bmh in the future, because BMH has changed to the provisioning state within 30s

https://github.com/metal3-io/cluster-api-provider-metal3/blob/c7c0a7df91eadfa5dbd97525c6229a25043951de/baremetal/metal3machine_manager.go#L327

**What did you expect to happen:**

machine can choose BMH

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

When creating a BMH, if ExternalProvisioned is false, it is not allowed to set the image field

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug
