### ISSUE TITLE
BMO reports a RegistrationError when managing iDRAC BMC hosts 

### ISSUE THREAD

**Issue by fracappa** [metal3-io/baremetal-operator#1339]
**Issue Details**

I'm currently using Metal3 to manage my Dell servers equipped with iDRAC BMCs. I've successfully set up a Kubernetes cluster using kubeadm and deployed the Bare Metal Operator (BMO) via the provided deploy.sh script.
This is how my bmc manifest looks like:

```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
     name: fall-bmh
spec:
  online: true
  bootMACAddress: <MAC-of-a-physical-NIC>
  bootMode: UEFI
  bmc:
    address: idrac-redfish://<iDRAC-IP>:443/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-credentials
    disableCertificateVerification: true
```
 However, when attempting to register my machines by creating custom BareMetalHost (bmh) resources, I encounter a RegistrationError. Reviewing the logs of the baremetal-operator-controller-manager, I found this message:

```
`{"level":"info","ts":"2023-08-24T13:52:32Z","logger":"controllers.BareMetalHost","msg":"publishing event","baremetalhost":{"name":"fall-bmh","namespace":"metal3"},"reason":"RegistrationError","message":"<Node-ID> failed verify step clear_job_queue with unexpected error: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)"}
{"level":"info","ts":"2023-08-24T13:52:32Z","logger":"controllers.BMCEventSubscription","msg":"start","bmceventsubscription":{"name":"fall-bmh","namespace":"metal3"}}
{"level":"info","ts":"2023-08-24T13:52:32Z","logger":"controllers.BMCEventSubscription","msg":"done","bmceventsubscription":{"name":"fall-bmh","namespace":"metal3"}}
{"level":"info","ts":"2023-08-24T13:52:32Z","logger":"controllers.BareMetalHost","msg":"done","baremetalhost":{"name":"fall-bmh","namespace":"metal3"},"provisioningState":"registering","requeue":false,"after":425.166795068}
`
```

**Expectation**

It seems the BMO receives a poorly formatted message from iDRAC. However, accessing the URL https://<iDRAC-IP>:443/redfish/v1/Systems/System.Embedded.1 directly in my browser yields a correctly formatted JSON. Therefore, I believe iDRAC is behaving correctly and is reachable, ruling out networking issues.

**Additional information**
Although I'm not sure if it's relevant, I'm operating a single-node Kubernetes cluster using kubeadm and tainting it with `kubectl taint nodes --all node-role.kubernetes.io/control-plane-`.

**Environment**

- Baremetal Operator version: v.0.3.1 (latest)
- iDRAC firmware version: 6.10.30.00

/kind bug
