### ISSUE TITLE
baremetal host timeout reached while inspecting the node

### ISSUE THREAD

**Issue by xinzhongyoumeng** [metal3-io/baremetal-operator#1472]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Using the following YAML file to create a baremetalhost:
```
apiVersion: v1
kind: Secret
metadata:
  name: bmh1
  namespace: baremetal-operator-system
type: Opaque
data:
  username: xxx
  password: xxx
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh1
  namespace: baremetal-operator-system
spec:
  online: true
  bootMACAddress: 6C:92:BF:AA:7C:2F
  bmc:
    address: 10.46.8.104:623
    credentialsName: bmh1
    disableCertificateVerification: true
---
apiVersion: v1
data:
  DEPLOY_KERNEL_URL: http://10.46.20.103:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://10.46.20.103:6180/images/ironic-python-agent.initramfs
    #DHCP_RANGE: 10.46.20.103-10.46.20.104
  HTTP_PROXY: http://xxxx
  HTTP_PORT: "6180"
  IRONIC_ENDPOINT: http://10.46.20.103:6385/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_KERNEL_PARAMS: console=ttyS0
  PROVISIONING_INTERFACE: eth0  # this inferface is which the ironic service node interface
kind: ConfigMap
```
The baremetalhost state is inspecting, such as :
```
kubectl get bmh -n baremetal-operator-system
NAME   STATE        CONSUMER   ONLINE   ERROR              AGE
bmh1   inspecting              true     inspection error   22h
```

kubectl -n baremetal-operator-system describe bmh
```
Name:         bmh1
Namespace:    baremetal-operator-system
Labels:       <none>
Annotations:  <none>
API Version:  metal3.io/v1alpha1
Kind:         BareMetalHost
Metadata:
  Creation Timestamp:  2023-11-30T07:53:11Z
  Finalizers:
    baremetalhost.metal3.io
  Generation:        1
  Resource Version:  2629556
  UID:               017fe67b-c3a4-4268-b938-92e8cb119f75
Spec:
  Automated Cleaning Mode:  metadata
  Bmc:
    Address:                           10.46.8.104:623
    Credentials Name:                  bmh1
    Disable Certificate Verification:  true
  Boot MAC Address:                    6C:92:BF:AA:7C:2F
  Online:                              true
Status:
  Error Count:    7
  Error Message:  timeout reached while inspecting the node
  Error Type:     inspection error
  Good Credentials:
    Credentials:
      Name:               bmh1
      Namespace:          baremetal-operator-system
    Credentials Version:  2286543
  Hardware Profile:       unknown
  Last Updated:           2023-12-01T05:31:00Z
  Operation History:
    Deprovision:
      End:    <nil>
      Start:  <nil>
    Inspect:
      End:    <nil>
      Start:  2023-11-30T07:53:22Z
    Provision:
      End:    <nil>
      Start:  <nil>
    Register:
      End:             2023-11-30T07:53:22Z
      Start:           2023-11-30T07:53:11Z
  Operational Status:  error
  Powered On:          false
  Provisioning:
    ID:         4554c5ba-112f-4e9a-8463-c58e4156129f
    Boot Mode:  UEFI
    Image:
      URL:
    Root Device Hints:
      Device Name:  /dev/sda
    State:          inspecting
  Tried Credentials:
    Credentials:
      Name:               bmh1
      Namespace:          baremetal-operator-system
    Credentials Version:  2286543
Events:
  Type    Reason           Age   From                         Message
  ----    ------           ----  ----                         -------
  Normal  InspectionError  56m   metal3-baremetal-controller  timeout reached while inspecting the node
```
I searched through the ironic service log, there is no userful infomation. 

The target baremetal host can see it rebooted, but it's os is previous.
**What did you expect to happen:**

The host can be ready.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The k8s version is v1.28.3

The baremetal-operator code is master

**Environment:**
OS: "Ubuntu 22.04 LTS
ALL IN ONE NODE

- Baremetal Operator version: master
- Environment (metal3-dev-env or other):

/kind bug
