### ISSUE TITLE
Need manually set boot from pxe when reinstall system

### ISSUE THREAD

**Issue by xinzhongyoumeng** [metal3-io/baremetal-operator#1498]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Using the following YAML file to create a baremetalhost:
```
apiVersion: v1
kind: Secret
metadata:
  name: bmh1
  namespace: baremetal-operator-system
type: Opaque
data:
  username: emhhbmd6aGVuaHVpCg==
  password: eWFjbkJ5bHUyOXYlMFk1alk1Cg==
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh1
  namespace: baremetal-operator-system
spec:
  online: true
  userData:
    name: cloud-init
    namespace: baremetal-operator-system
  bootMACAddress: xxx
  bmc:
    address: 10.46.8.102:623
    credentialsName: bmh1
    disableCertificateVerification: true
```
and the ironic deployment  configmap is 
```
apiVersion: v1
data:
  DEPLOY_KERNEL_URL: http://10.46.72.2:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://10.46.72.2:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: xxx
  HTTP_PORT: "6180"
  INSPECTOR_REVERSE_PROXY_SETUP: "false"
  IRONIC_ENDPOINT: http://10.46.72.2:6385/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_KERNEL_PARAMS: console=ttyS0
  PROVISIONING_INTERFACE: eth0
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
kind: ConfigMap
```
Before I apply this yaml, I need manually set boot from pxe, so that can reinstall system. Otherwise，the server only reboot.
After reinstall system complete，reboot，it also boot from original system. 
**What did you expect to happen:**

When reinstall system complete, reboot ,it can boot from new system.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Only deployed baremetal operator and ironic deployment
- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

**Comment by xinzhongyoumeng** [comment]
Another quetion is how to set bmh user and password, when I set it by userdata，it seem not to be working.
```
cat cloud-config
userData: |
  #cloud-config
  users:
  - name: testuser
    passwd: xxx
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, wheel
```
kubectl create secret generic cloud-init --from-file=userData=cloud-config -n baremetal-operator-system
