### ISSUE TITLE
One BMO controls multiple Ironic

### ISSUE THREAD

**Issue by matthewei** [metal3-io/baremetal-operator#1667]
**User Story**
We have many data centers scattered across the country, and we want to create a BMO on the central cloud to manage the ironic of each data center, to achieve the creation of bare metal k8s clusters.

**Detailed Description**

[A clear and concise description of what you want to happen.]
One BMO can manage several Ironic.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by dtantsur** [comment]
This is an interesting request, but it's going to be tricky. For instance: how does BMO know, which Ironic to talk to for each specific BareMetalHost? What should BMO do what only some of the Ironics are available? Should we support migrating hosts between Ironics (if yes, how?)?

On a related note, make sure [conductor groups](https://docs.openstack.org/ironic/latest/admin/conductor-groups.html) don't solve your problems.

**Comment by Rozzii** [comment]
/triage accepted
This is a legit feature request but it will be a long design process as far as I can tell, as part of the written proposal  we would need to hear about some good justifications of "why multiple Ironic instances can be deployed but not multiple BMOs" .

**Comment by matthewei** [comment]
> /triage accepted This is a legit feature request but it will be a long design process as far as I can tell, as part of the written proposal we would need to hear about some good justifications of "why multiple Ironic instances can be deployed but not multiple BMOs" .

I would like to write an article to explain it.

**Comment by matthewei** [comment]
[One BMO controls multiple Ironic.pdf](https://github.com/metal3-io/baremetal-operator/files/15244947/One.BMO.controls.multiple.Ironic.pdf)
@Rozzii @dtantsur  Please check the attachment.

**Comment by eidmantas** [comment]
@Rozzii @dtantsur  wanted to ask - https://docs.openstack.org/ironic/latest/admin/conductor-groups.html 
is there currently some way to utilize this?

**Comment by dtantsur** [comment]
> is there currently some way to utilize this?

There is none right now.

By the way, I'm also pondering potential way to span Ironic across multiple sites. Essentially, the options I'm considering are:

1. Several Ironics merged by BMO (your proposal). I guess we could have an immutable field on BMH that specifies which Ironic to use. What sort of a reference is that? I don't know yet. Maybe an explicit field with an address, a credentials secret and a TLS secret.
2. One Ironic with remote conductor groups on remote workers. Easier from BMO's perspective, more complex on the IrSO (or whichever way you deploy Ironic) side. Will mandate using a separate database, which will need to be accessed publicly (ugh). Same for conductor RPC.

**Comment by dtantsur** [comment]
> Maybe an explicit field with an address, a credentials secret and a TLS secret

Hmm. This makes sense from API perspective but will be a proper nightmare from the internal code organization. Ideally, we need to know a list of Ironic references in advance, so that we can prepare and cache clients. Or at least somehow manage clients without opening a new connection to Ironic each time we reconcile a host.

Could be worth a new CRD. Like

```yaml
---
apiVersion: metal3.io/v1alpha1
kind: IronicReference
metadata:
  name: local-ironic
  namespace: baremetal-operator-system
spec:
  address: https://ironic.ironic-ns.svc
  credentialsName: local-ironic-auth
  tlsName: local-ironic-tls
---
apiVersion: metal3.io/v1alpha1
kind: IronicReference
metadata:
  name: site1-ironic
  namespace: baremetal-operator-system
spec:
  address: https://site1.example.com:6385
  credentialsName: site1-ironic-auth
  tlsName: site1-ironic-tls
---
apiVersion: metal3.io/v1alpha1
kind: IronicReference
metadata:
  name: irso-deployed-ironic
  namespace: baremetal-operator-system
spec:
  ironicName: name-of-irso-ironic-object
```

BMO could be started with `DEFAULT_IRONIC=local-ironic` and would listen to all IronicRefereces in its namespace to be able to cache clients. A BMH would then have an `ironicName` field.

(not a well thought proposal, just dumping ideas!)
