### ISSUE TITLE
Operational history for BMH is not displayed

### ISSUE THREAD

**Issue by yprokule** [metal3-io/baremetal-operator#177]
Problem description
================
Events about BMH state transition is not displayed with resource describe:
```
oc describe baremetalhost discovered-node-0 -n openshift-machine-api
Name:         discovered-node-0
Namespace:    openshift-machine-api
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"metalkube.org/v1alpha1","kind":"BareMetalHost","metadata":{"annotations":{},"name":"discovered-node-0","namespace":"openshi...
API Version:  metalkube.org/v1alpha1
Kind:         BareMetalHost
Metadata:
  Creation Timestamp:  2019-05-03T09:19:31Z
  Finalizers:
    baremetalhost.metalkube.org
  Generation:        2
  Resource Version:  350682
  Self Link:         /apis/metalkube.org/v1alpha1/namespaces/openshift-machine-api/baremetalhosts/discovered-node-0
  UID:               8f2d0fbb-6d84-11e9-b472-525400a4453e
Spec:
  Bmc:
    Address:           
    Credentials Name:  discovered-node-0-bmc-secret
  Boot MAC Address:    52:54:00:b7:e8:e8
  Hardware Profile:    
  Online:              true
Status:
  Error Message:  Empty BMC address Missing BMC connection detail 'Address'
  Good Credentials:
  Hardware Profile:    
  Last Updated:        2019-05-03T09:19:31Z
  Operational Status:  discovered
  Powered On:          false
  Provisioning:
    ID:  
    Image:
      Checksum:  
      URL:       
    State:       
Events:          <none>
```
While in `baremetal-operator` logs:
```
{"level":"info","ts":1556875171.6777682,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"openshift-machine-api","Request.Name":"discovered-node-0"}
{"level":"info","ts":1556875171.6778715,"logger":"baremetalhost","msg":"adding finalizer","Request.Namespace":"openshift-machine-api","Request.Name":"discovered-node-0","existingFinalizers":[],"newValue":"bareme
talhost.metalkube.org"}
{"level":"info","ts":1556875171.6889548,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"openshift-machine-api","Request.Name":"discovered-node-0"}
{"level":"info","ts":1556875171.6891785,"logger":"baremetalhost","msg":"updating owner of secret","Request.Namespace":"openshift-machine-api","Request.Name":"discovered-node-0"}
{"level":"info","ts":1556875171.7072365,"logger":"baremetalhost","msg":"publishing event","reason":"Discovered","message":"Discovered host with unusable BMC details: Empty BMC address Missing BMC connection deta
il 'Address'"}
{"level":"info","ts":1556875171.726009,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"openshift-machine-api","Request.Name":"discovered-node-0"}
```
Steps to reproduce
===============
1. Create BMH CR with _missing_  BMC details, for e.g.:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: discovered-node-0-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

# BMC address intentionally left empty to trigger transition
# to 'Discovered' state
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: discovered-node-0
spec:
  online: true
  bmc:
    address:
    credentialsName: discovered-node-0-bmc-secret
  bootMACAddress: 52:54:00:b7:e8:e8
```

2. Realize those resources:
```
oc apply -f discovered_node_cr.yaml -n openshift-machine-api
```

3. Check resource's defintion
```
oc describe baremetalhost discovered-node-0 -n openshift-machine-api
```
