### ISSUE TITLE
Expose hostname provided by DHCP in introspection data

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#190]
Currently, the network info we have on a BareMetalHost looks like this:

```
      nics:
      - ip: 172.22.0.86
        mac: 00:5a:10:3f:c2:3d
        model: 0x1af4 0x0001
        name: eth0
        network: Pod Networking
        speedGbps: 0
      - ip: 192.168.111.21
        mac: 00:5a:10:3f:c2:3f
        model: 0x1af4 0x0001
        name: eth1
        network: Pod Networking
        speedGbps: 0
```

If a hostname is provided by DHCP, I would like to see it as a new field in here.

This is needed by https://github.com/metal3-io/cluster-api-provider-baremetal/issues/49

The issue is that we eventually need all of the addresses that show up on a Node to also be in the Machine status.  Right now that includes both IP and hostname.  The info we have so far will let us populate the Machine status field with the expected IPs, but not hostname.
