### ISSUE TITLE
BMO doesn't retry on a host with wrong bmc credentials

### ISSUE THREAD

**Issue by yprokule** [metal3-io/baremetal-operator#195]
If a BMH CRD has wrong credentials, host  is added but is not retried even after credentials were fixed.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-node-4-bmc-secret
type: Opaque
data:
  username: YmFkdXNlcgo=
  password: YmFkcGFzcwo=

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-node-4
spec:
  online: true
  bmc:
    address: ipmi://192.168.122.1:6234
    credentialsName: openshift-node-4-bmc-secret
  bootMACAddress: 52:54:00:32:78:1a
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2.md5sum"
```
_BMH_ ends up in error state:
```
Events:
  Type    Reason             Age   From                         Message
  ----    ------             ----  ----                         -------
  Normal  Registered         15m   metal3-baremetal-controller  Registered new host
  Normal  RegistrationError  15m   metal3-baremetal-controller  Failed to get power state for node 65e845dc-7a5c-4e13-96f7-5f29639e4a28. Error: IPMI call failed: power status.
```
and is not retried even after the credentials are fixed

```
{"level":"info","ts":1558441798.9009247,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"openshift-machine-api","Request.Name":"openshift-node-4"}
{"level":"info","ts":1558441798.9010067,"logger":"baremetalhost_ironic","msg":"ironic settings","endpoint":"http://localhost:6385/v1/","inspectorEndpoint":"http://localhost:5050/v1/","deployKernelURL":"http://172.22.0.1/images/ironic-python-agent.kernel","deployRamdiskURL":"http://172.22.0.1/images/ironic-python-agent.initramfs"}
{"level":"info","ts":1558441798.9010217,"logger":"baremetalhost","msg":"registering and validating access to management controller","Request.Namespace":"openshift-machine-api","Request.Name":"openshift-
node-4","provisioningState":"registering"}
{"level":"info","ts":1558441798.9010265,"logger":"baremetalhost_ironic","msg":"validating management access","host":"openshift-node-4"}
{"level":"info","ts":1558441798.92309,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"openshift-node-4"}
{"level":"info","ts":1558441798.9481359,"logger":"baremetalhost","msg":"stopping on host error","Request.Namespace":"openshift-machine-api","Request.Name":"openshift-node-4","provisioningSta
te":"registering","message":"Failed to get power state for node 65e845dc-7a5c-4e13-96f7-5f29639e4a28. Error: IPMI call failed: power status."}
```
```
{
    "apiVersion": "v1",
    "data": {
        "password": "Z29vZHBhc3N3b3JkCg==",
        "username": "Z29vZHVzZXIK"
    },
    "kind": "Secret",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":{\"password\":\"Z29vZHBhc3N3b3JkCg==\",\"username\":\"Z29vZHVzZXIK\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"openshift-node-4-bmc-secret\",\"namespace\":\"openshift-machine-api\"},\"type\":\"Opaque\"}\n"
        },
        "creationTimestamp": "2019-05-21T12:28:59Z",
        "name": "openshift-node-4-bmc-secret",
        "namespace": "openshift-machine-api",
        "ownerReferences": [
            {
                "apiVersion": "metal3.io/v1alpha1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "BareMetalHost",
                "name": "openshift-node-4",
                "uid": "02aae0a7-7bc4-11e9-abd0-525400f8c71d"
            }
        ],
        "resourceVersion": "287714",
        "selfLink": "/api/v1/namespaces/openshift-machine-api/secrets/openshift-node-4-bmc-secret",
        "uid": "02a8cb40-7bc4-11e9-abd0-525400f8c71d"
    },
    "type": "Opaque"
}```
