### ISSUE TITLE
Unable to find a valid partition table on the disk after writing the image

### ISSUE THREAD

**Issue by mkosobucki-relspace** [metal3-io/baremetal-operator#2517]
**What steps did you take and what happened:**
I have prepared a baremetal image with:

```
export DIB_RELEASE=jammy
disk-image-create -x --no-tmpfs -t raw -o output.raw baremetal block-device-efi ubuntu-minimal

```
Using:
```
disk-image-create --version
3.38.0
```
Installed baremetal-operator from branch release-0.10 using from tools directory:
```
/deploy.sh -b -i -t 
```
Created secrets for RedFish credentials and with ssh-key:
```
$cat secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: dell-idrac
type: Opaque
stringData:
  username: ***
  password:  ***
```
```
$cat user-data.yaml 

#cloud-config
users:
- name: user
  ssh_authorized_keys:
  - ssh-rsa ***
```
Then created instance of BareMetalHost that will use previously created secrets (all in default namespace):
```
$ cat my-baremetal-host

apiVersion: metal3.io/v1alpha1
kind: BareMetalHost     
metadata:
  name: my-baremetal-host
spec:
  online: true
  rootDeviceHints:
    deviceName: "/dev/sda"
  automatedCleaningMode: metadata
  bootMACAddress: B8:E9:24:AA:FD:44
  bootMode: UEFI
  bmc:
    address: idrac-virtualmedia://***:443/redfish/v1/Systems/System.Embedded.1   
    credentialsName: dell-idrac
    disableCertificateVerification: true
  image:
    checksumType: sha256    
    checksum: http://***/SHA256SUMS
    format: qcow2
    url: http://***/jammy-server-cloudimg-amd64.img 
  userData:
    name: user-data
    namespace: default
```
Created from manifests (in default namespace):
```
kubectl -f secrets.yaml
kubectl -f user-data.yaml
kubectl -f my-baremetal-host.yaml
```
It went through the process of mounting a virtual CD and inspecting it but after deploying hit error when looking at `kubectl describe baremetal my-baremetal-host`:
```
{"level":"info","ts":1747082089.2509487,"logger":"provisioner.ironic","msg":"current provision state","host":"default~wormhole-k8s-012","lastError":"Deploy step deploy.write_image failed on node 7721932f-1d88-474a-875f-7fca369ab255. Unable to find a valid partition table on the disk after writing the image. The image may be corrupted. Error: Unexpected error while running command.\nCommand: parted -s -m /dev/sda unit MiB print\nExit code: 1\nStdout: 'BYT;\\n/dev/sda:457344MiB:scsi:4096:4096:unknown:DELL RAID:;\\n'\nStderr: 'Error: /dev/sda: unrecognised disk label\\n'","current":"wait call-back","target":"active"} 
```

**What did you expect to happen:**
I expected validation to pass and to boot into user image (Ubuntu in this case).

**Anything else you would like to add:**
Baremetal hardware in use: PowerEdge R6625
RAID controller used: PERC H965i Front (Embedded) with preconfigured RAID0 with 2 x 446GB SSDs

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Baremetal Operator version: release-0.10
- Environment (metal3-dev-env or other): Baremetal

/kind bug

**Comment by Rozzii** [comment]
There is really not much to do AFAIK, in Ironic terms this is a "whole disk image" deployment so the image is written to the disk without any partitioning steps (except the config drive).

I suspect that you have a miss-match in the image types, you created a raw image according to the info you have shared but then specified qcow2 as the image format on the BMH manifest. If qcow2 is selected then the deployment will be done a bit differently compared to raw, also you would be unable to benefit from raw image streaming.

**Comment by mkosobucki-relspace** [comment]
Thank you for a response. My understanding is:
* image, I am using (it is official image I did not build) is NOT a whole image but with partitions:
```
$ sudo virt-filesystems --long --all -a jammy-server-cloudimg-amd64.img 
Name       Type       VFS     Label           MBR Size       Parent
/dev/sda1  filesystem ext4    cloudimg-rootfs -   2244984320 -
/dev/sda14 filesystem unknown -               -   4194304    -
/dev/sda15 filesystem vfat    UEFI            -   111149056  -
/dev/sda1  partition  -       -               -   2244984320 /dev/sda
/dev/sda14 partition  -       -               -   4194304    /dev/sda
/dev/sda15 partition  -       -               -   111149056  /dev/sda
/dev/sda   device     -       -               -   2361393152 -
```

* it is in qcow2 format:
```
$ file jammy-server-cloudimg-amd64.img 
jammy-server-cloudimg-amd64.img: QEMU QCOW2 Image (v2), 2361393152 bytes
```
* I have no mismatch, as I specified qcow2:
```
format: qcow2.  <--------------
```
1. What is the recommendation in terms of building an image (whole or partitionned) for Ironic?
2. How does IPA determines whether it is whole vs partitioned (maybe I am missing config)?
3. Is raw prefered over qcow2 due to streaming?

**Comment by mkosobucki-relspace** [comment]
Status update on my end. I have done the following:
1. Deleted host from Ironic
2. Using iDRAC interface deleter RAID 1 Virtual Disk
3. Converted only one disk to Non-RAID and confirmed that it also shows as /dev/sda
4. Added host back to Ironic skipping "image" and "userData"
5. Confirmed that it went through inspection successfully
6. Added "image" and "userData"
7. Confirmed it completed provisioning, passed validation and booted to OS

It appears that RAID 1 from some reasons breaks it. I do not see a good reason as it is detecting a block device.
*RAID result of inspection:*
```
    storage:
    - alternateNames:
      - /dev/sda
      - /dev/disk/by-path/pci-0000:41:00.0-scsi-0:0:1:0
      hctl: "5:0:1:0"
      model: RAID
      name: /dev/disk/by-path/pci-0000:41:00.0-scsi-0:0:1:0
      serialNumber: 0095bf994396989e670061097b80e04e
      sizeBytes: 479559942144
      type: SSD
      vendor: DELL
      wwn: 0x6f4ee0807b096100679e98964399bf95
      wwnVendorExtension: "0x679e98964399bf95"
      wwnWithExtension: 0x6f4ee0807b096100679e98964399bf95
    systemVendor:
```
*Non-RAID result of inspection:*
```                                                                                                                          
    storage:
    - alternateNames:
      - /dev/sda
      - /dev/disk/by-path/pci-0000:41:00.0-scsi-0:0:275:0
      hctl: 1:0:275:0
      model: MTFDDAK480TGA-1BC1ZABDA
      name: /dev/disk/by-path/pci-0000:41:00.0-scsi-0:0:275:0
      serialNumber: 24454CD7431E
      sizeBytes: 480103981056
      type: SSD
      vendor: ATA
      wwn: "0x500a07514cd7431e"
      wwnWithExtension: "0x500a07514cd7431e" 
```
Does anyone have any ideas what this could be? Why only non-RAID setup works?
