### ISSUE TITLE
Simplify configmap required parameters

### ISSUE THREAD

**Issue by hardys** [metal3-io/baremetal-operator#269]
Currently to launch a BMO with ironic we need a configmap similar to:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ironic-bmo-configmap
data:
  http_port: "6180"
  provisioning_interface: "ens3"
  provisioning_ip: "172.22.0.3/24"
  dhcp_range: "172.22.0.10,172.22.0.100"
  deploy_kernel_url: "http://172.22.0.3:6180/images/ironic-python-agent.kernel"
  deploy_ramdisk_url: "http://172.22.0.3:6180/images/ironic-python-agent.initramfs"
  ironic_endpoint: "http://172.22.0.3:6385/v1/"
  ironic_inspector_endpoint: "http://172.22.0.3:5050/v1/"
```
Ref https://github.com/openshift-metal3/dev-scripts/blob/master/ironic_bmo_configmap.yaml

I think we can simplify this, because several of these options are either provided elsewhere (e.g the kernel/ramdisk is in the machine providerSpec for OpenShift, need to confirm how this works with upstream testing), and some (all the endpoints) are an internal implementation detail.

I'd suggest that we at least set some defaults for these parameters, since Ironic is supposed to be an internal implementation detail, and we can probably set sane defaults for deploy_kernel_url,  deploy_ramdisk_url,  ironic_endpoint,  and ironic_inspector_endpoint based on the existing parameters e.g provisioning_ip and http_port.

An alternative option for the endpoints could be to make use of the recently added mdns advertisement of endpoints, or perhaps more simply the Ironic API containers could write their endpoint to the shared volume on startup?

Regardless of the approach I think we need to sanitise and simplify this interface to hide the internal Ironic interfaces.
