### ISSUE TITLE
No Provisioning Status visible for newly created baremetalhost 

### ISSUE THREAD

**Issue by tssavita** [metal3-io/baremetal-operator#370]
I tried creating a baremetalhost with the following YAML file, on my baremetal Kubernetes cluster. 
```
---
apiVersion: v1
kind: Secret
metadata:
  name: bm-2-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bm-2
spec:
  online: true
  bootMACAddress: ff:ff:ff:ff:ff:ff
  bmc:
    address: ipmi://x.x.x.x
    credentialsName: bm-2-bmc-secret
```
The following is the result I get. 
![image](https://user-images.githubusercontent.com/2744118/71086321-eb52b380-2199-11ea-9937-69c7c9ae7451.png)

I can't see the Provisioning Status switching from Inspecting to Ready. I can't see any value for Provisioning Status. 

Is there something extra I need to specify in the YAML file?
