### ISSUE TITLE
Baremetalhost Provisioning Status stuck in Inspecting State

### ISSUE THREAD

**Issue by tssavita** [metal3-io/baremetal-operator#393]
Using the following YAML file to create a baremetalhost: 
```
---
apiVersion: v1
kind: Secret
metadata:
  name: bm-secret103
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bm-host103
spec:
  online: true
  bmc:
    address: ipmi://10.4.29.12
    credentialsName: bm-secret103
```
The target baremetalhost's network interface gets an IP from the ironic-dnsmasq container. I can see also see the PXE bootloader files being transferred through TFTP. 
From this video: https://www.youtube.com/watch?v=KIIkVD7gujY, I gathered that I need to wait for the Provisioning Status to change to *Ready*, before I can edit the baremetalhost image and checksum URLs. But the Provisioning Status is stuck in *Inspecting* State.
