### ISSUE TITLE
Error in Image Validation -   Max retries exceeded with url: /images/bionic-server-cloudimg-amd64.img

### ISSUE THREAD

**Issue by rkamudhan** [metal3-io/baremetal-operator#428]
I using the latest code in my setup,
I am provisioning two servers and I am getting following error:
```
# kubectl get bmh -n metal3
NAME            STATUS   PROVISIONING STATUS   CONSUMER   BMC                   HARDWARE PROFILE   ONLINE   ERROR
edge01-node01   OK       provisioning                     ipmi://10.10.110.11   unknown            true
edge01-node02   error    deprovisioning                   ipmi://10.10.110.13   unknown            true     host validation error: Validation of image href http://172.22.0.1/images/bionic-server-cloudimg-amd64.img failed, reason: HTTPConnectionPool(host='172.22.0.1', port=80): Max retries exceeded with url: /images/bionic-server-cloudimg-amd64.img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27a1cb96d8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)); Validation of image href http://172.22.0.1/images/bionic-server-cloudimg-amd64.img failed, reason: HTTPConnectionPool(host='172.22.0.1', port=80): Max retries exceeded with url: /images/bionic-server-cloudimg-amd64.img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27a1fc7fd0>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))
```
And httpd container logs are as follows:
```
k# docker logs -f httpd
Waiting for provisioning interface to be configured
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Thu Feb 13 05:33:09.397863 2020] [suexec:notice] [pid 1:tid 140393017612544] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Thu Feb 13 05:33:09.412624 2020] [lbmethod_heartbeat:notice] [pid 1:tid 140393017612544] AH02282: No slotmem from mod_heartmonitor
[Thu Feb 13 05:33:09.413334 2020] [http2:warn] [pid 1:tid 140393017612544] AH02951: mod_ssl does not seem to be enabled
[Thu Feb 13 05:33:09.416119 2020] [mpm_event:notice] [pid 1:tid 140393017612544] AH00489: Apache/2.4.37 (centos) configured -- resuming normal operations
[Thu Feb 13 05:33:09.416136 2020] [core:notice] [pid 1:tid 140393017612544] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /dualboot.ipxe HTTP/1.1" 200 741 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /pxelinux.cfg/00-1e-67-fc-fc-b0 HTTP/1.1" 404 228 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /pxelinux.cfg/00-1e-67-fc-fc-b0 HTTP/1.1" 404 228 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /inspector.ipxe HTTP/1.1" 200 623 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /images/ironic-python-agent.kernel HTTP/1.1" 200 6734016 "-" "iPXE/1.0.0+ (3fe68)"

gzip: stdout: Broken pipe
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /dualboot.ipxe HTTP/1.1" 200 741 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /pxelinux.cfg/00-1e-67-f1-5b-91 HTTP/1.1" 404 228 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /pxelinux.cfg/00-1e-67-f1-5b-91 HTTP/1.1" 404 228 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /inspector.ipxe HTTP/1.1" 200 623 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /images/ironic-python-agent.kernel HTTP/1.1" 200 6734016 "-" "iPXE/1.0.0+ (3fe68)"

gzip: stdout: Broken pipe
172.22.0.21 - - [13/Feb/2020:06:00:46 +0000] "GET /images/ironic-python-agent.initramfs HTTP/1.1" 200 402401036 "-" "iPXE/1.0.0+ (3fe68)"
172.22.0.60 - - [13/Feb/2020:06:00:48 +0000] "GET /images/ironic-python-agent.initramfs HTTP/1.1" 200 402401036 "-" "iPXE/1.0.0+ (3fe68)"
```
Any pointer will be helpful.

**Comment by andy-v-h** [comment]
Could you provide a `kubectl get pods -nmetal3 -owide` ?
My suspicion is your pod is on a different IP, and possibly a different L2 network domain.  The default options don't set a DNS or Router with DNSMASQ.  Also, you do you have `iptables` causing an issue?

**Comment by rkamudhan** [comment]
@andy-v-h the issues with https_port, in the script it has been changed into 6180, I didn't add it in my CR. After adding it this error is resolved :), I am hitting another issue as below.

I am running ironic locally with the following environment
```
#cat ironic_ci.env
HTTP_PORT=6180
PROVISIONING_INTERFACE=provisioning
DHCP_RANGE=172.22.0.10,172.22.0.100
DEPLOY_KERNEL_URL=http://172.22.0.1:6180/images/ironic-python-agent.kernel
DEPLOY_RAMDISK_URL=http://172.22.0.1:6180/images/ironic-python-agent.initramfs
IRONIC_ENDPOINT=http://172.22.0.1:6385/v1/
IRONIC_INSPECTOR_ENDPOINT=http://172.22.0.1:5050/v1/
CACHEURL=http://172.22.0.1/images
IRONIC_FAST_TRACK=true
```
and running the no_ironic operator as follows,
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metal3-baremetal-operator
  template:
    metadata:
      labels:
        name: metal3-baremetal-operator
    spec:
      serviceAccountName: metal3-baremetal-operator
      containers:
        - name: baremetal-operator
          image: quay.io/metal3-io/baremetal-operator:master
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /baremetal-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "baremetal-operator"
            - name: DEPLOY_KERNEL_URL
              value: "http://172.22.0.1:6180/images/ironic-python-agent.kernel"
            - name: DEPLOY_RAMDISK_URL
              value: "http://172.22.0.1:6180/images/ironic-python-agent.initramfs"
            - name: IRONIC_ENDPOINT
              value: "http://localhost:6385/v1/"
            - name: IRONIC_INSPECTOR_ENDPOINT
              value: "http://localhost:5050/v1/"
        # Temporary workaround to talk to an external Ironic process until Ironic is running in this pod.
        - name: ironic-proxy
          image: alpine/socat
          command: ["socat", "tcp-listen:6385,fork,reuseaddr", "tcp-connect:172.22.0.1:6385"]
          imagePullPolicy: Always
        - name: ironic-inspector-proxy
          image: alpine/socat
          command: ["socat", "tcp-listen:5050,fork,reuseaddr", "tcp-connect:172.22.0.1:5050"]
          imagePullPolicy: Always
```
My CR as follows:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: edge01-node01-bmc-secret
type: Opaque
data:
  username: cm9vdA==
  password: cm9vdA==

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: edge01-node01
spec:
  online: true
  bmc:
    address: ipmi://10.10.110.11
    credentialsName: edge01-node01-bmc-secret
  image:
    url: http://172.22.0.1:6180/images/bionic-server-cloudimg-amd64.img
    checksum: http://172.22.0.1:6180/images/bionic-server-cloudimg-amd64.img.md5sum
  userData:
    name: edge01-node01-user-data
    namespace: metal3
```
After it my nodes changes from provisioning to deprovisioning state:
When I looked into the baremetal-operator logs, I am getting following error
```
{"level":"info","ts":1581622940.730746,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"edge01-node02"}
{"level":"info","ts":1581622940.730974,"logger":"baremetalhost","msg":"provisioning","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning"}
{"level":"info","ts":1581622940.7742665,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"edge01-node02"}
{"level":"info","ts":1581622940.7743046,"logger":"baremetalhost_ironic","msg":"provisioning image to host","host":"edge01-node02","state":"deploy failed"}
{"level":"info","ts":1581622940.7743223,"logger":"baremetalhost_ironic","msg":"checking image settings","host":"edge01-node02","source":"http://172.22.0.1:6180/images/bionic-server-cloudimg-amd64.img","checksum":"http://172.22.0.1:6180/images/bionic-server-cloudimg-amd64.img.md5sum","same":true,"provisionState":"deploy failed"}
{"level":"info","ts":1581622940.7743368,"logger":"baremetalhost_ironic","msg":"found error","host":"edge01-node02","msg":"Failed to deploy: {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}"}
{"level":"info","ts":1581622940.7743504,"logger":"baremetalhost","msg":"handling provisioning error in controller","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning"}
{"level":"info","ts":1581622940.7743785,"logger":"baremetalhost","msg":"changing provisioning state","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning","old":"provisioning","new":"provisioning error"}
{"level":"info","ts":1581622940.7744048,"logger":"baremetalhost","msg":"saving host status","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning","operational status":"error","provisioning state":"provisioning error"}
{"level":"info","ts":1581622940.784938,"logger":"baremetalhost","msg":"publishing event","reason":"ProvisioningError","message":"Image provisioning failed: Failed to deploy: {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}"}
{"level":"info","ts":1581622940.791047,"logger":"baremetalhost","msg":"stopping on host error","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning","message":"Image provisioning failed: Failed to deploy: {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}"}
{"level":"info","ts":1581622940.7911217,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"edge01-node02"}
{"level":"info","ts":1581622940.791249,"logger":"baremetalhost","msg":"changing provisioning state","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning error","old":"provisioning error","new":"deprovisioning"}
{"level":"info","ts":1581622940.7912881,"logger":"baremetalhost","msg":"saving host status","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning error","operational status":"error","provisioning state":"deprovisioning"}
{"level":"info","ts":1581622940.8056731,"logger":"baremetalhost","msg":"done","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"provisioning error","requeue":true,"after":0}
{"level":"info","ts":1581622940.80588,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"edge01-node02"}
{"level":"info","ts":1581622940.8059974,"logger":"baremetalhost","msg":"deprovisioning","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"deprovisioning"}
{"level":"info","ts":1581622940.8060193,"logger":"baremetalhost_ironic","msg":"deprovisioning","host":"edge01-node02"}
{"level":"info","ts":1581622940.847085,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"edge01-node02"}
{"level":"info","ts":1581622940.8471148,"logger":"baremetalhost_ironic","msg":"deprovisioning host","host":"edge01-node02","ID":"c9d34929-b0e4-4320-ade2-a786dac64d01","lastError":"Failed to deploy: {'step': 'deploy', 'priority': 100, 'argsinfo': None, 'interface': 'deploy'}","current":"deploy failed","target":"active","deploy step":{}}
{"level":"info","ts":1581622940.847142,"logger":"baremetalhost_ironic","msg":"starting deprovisioning","host":"edge01-node02"}
{"level":"info","ts":1581622940.8471549,"logger":"baremetalhost_ironic","msg":"changing provisioning state","host":"edge01-node02","current":"deploy failed","existing target":"active","new target":"deleted"}
{"level":"info","ts":1581622940.9757707,"logger":"baremetalhost","msg":"saving host status","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"deprovisioning","operational status":"OK","provisioning state":"deprovisioning"}
{"level":"info","ts":1581622940.985292,"logger":"baremetalhost","msg":"publishing event","reason":"DeprovisioningStarted","message":"Image deprovisioning started"}
{"level":"info","ts":1581622941.0038836,"logger":"baremetalhost","msg":"done","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"deprovisioning","requeue":true,"after":10}
{"level":"info","ts":1581622941.0039637,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"edge01-node02"}
{"level":"info","ts":1581622941.0041037,"logger":"baremetalhost","msg":"deprovisioning","Request.Namespace":"metal3","Request.Name":"edge01-node02","provisioningState":"deprovisioning"}
```

And getting this weird state changes from provisioning to de-provisioning continuously
