### ISSUE TITLE
BMH properties are not always applied correctly

### ISSUE THREAD

**Issue by ismacasti** [metal3-io/baremetal-operator#452]
Hi!

Using this _baremetalhost_ definition:
```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker6
  namespace: metal3
  labels:
    node.type: worker
    node.uuid: 8cc80401-fd3f-dc47-844f-2b89a86d4190
spec:
  bmc:
    address: redfish://10.33.131.4/redfish/v1/Systems/8cc80401-fd3f-dc47-844f-2b89a86d4190
    credentialsName: worker6
    disableCertificateVerification: true
  bootMACAddress: "90:38:09:ac:ae:97"
  online: true
```

When applied (`kubectl apply -f worker6.yaml`), registration fails with TLS errors, and `kubectl get bmh worker6 -o yaml` shows this:
```
---8<---
spec:
  bmc:
    address: redfish://10.33.131.4/redfish/v1/Systems/8cc80401-fd3f-dc47-844f-2b89a86d4190
    credentialsName: worker6
  bootMACAddress: 90:38:09:ac:ae:97
  consumerRef:
---8<---
```

The `disableCertificateVerification: true` is gone.
If I apply the bmh definition again, then it works. :
```
---8<---
spec:
  bmc:
    address: redfish://10.33.131.4/redfish/v1/Systems/8cc80401-fd3f-dc47-844f-2b89a86d4190
    credentialsName: worker6
    disableCertificateVerification: true
  bootMACAddress: 90:38:09:ac:ae:97
  consumerRef:
---8<---
```
Now everything works just fine.
It seems that the disableCertificateVerification property gets lost somewhere, and only sometimes, around 1/3 of the bmh created.
As reapplying the same YAML fixes it, a workaround is just to add the bmh creation in a short loop.

It happens on commit `4b4f065f`.

Thanks!
