### ISSUE TITLE
Autocleaning tries to clean all devices even when setting rootDeviceHints

### ISSUE THREAD

**Issue by ismacasti** [metal3-io/baremetal-operator#596]
Hi!

Using metal3 on a HPE machine fails to deploy due to errors on auto_clean step:

```
2020-07-16 12:11:24.790 27 ERROR ironic.drivers.modules.agent_base [-] Agent returned error for clean step {'reboot_requested': False, 'abortable': True, 'priority': 10, 'step': 'erase_devices_metadata', 'interface': 'deploy'} on node 6bc12e1b-2bcd-4260-843e-9504f647e303 : {'message': 'Clean step failed: Error performing clean_step erase_devices_metadata: Error erasing block device: Failed to erase the metadata on the device(s): "/dev/sdb": Unexpected error while running command.\nCommand: wipefs --all /dev/sdb\nExit code: 1\nStdout: u\'\'\nStderr: u\'wipefs: error: /dev/sdb: probing initialization failed: Read-only file system\\n\'', 'code': 500, 'type': 'CleaningError', 'details': 'Error performing clean_step erase_devices_metadata: Error erasing block device: Failed to erase the metadata on the device(s): "/dev/sdb": Unexpected error while running command.\nCommand: wipefs --all /dev/sdb\nExit code: 1\nStdout: u\'\'\nStderr: u\'wipefs: error: /dev/sdb: probing initialization failed: Read-only file system\\n\''}.
```

Here's the BareMetalHost definition:
```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: syn480x5371
  namespace: metal3
  labels:
    node-pool-name: control-plane
spec:
  bmc:
    address: redfish://10.223.100.215/redfish/v1/Systems/1
    credentialsName: bmc-syn480x5371
    disableCertificateVerification: true
  bootMACAddress: "82:81:1C:80:00:39"
  rootDeviceHints:
    deviceName: "/dev/nvme0n1"
  online: false
```

This causes problems on these particular machines, as /dev/sdb is a read-only device (some kind of firmware drive).
In my opinion, Ironic should only clean the device set in the hint, if it is set.

I'm not sure this issue should be filed here on in the ironic-image repo. Please move if it necessary.

Thanks for your help!
-- Ismael
