### ISSUE TITLE
no kind "BareMetalHost" is registered for version "metal3.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

### ISSUE THREAD

**Issue by FaridHub** [metal3-io/baremetal-operator#604]
Issue:
**error: no kind "BareMetalHost" is registered for version "metal3.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"**

Problem description:
I am trying to provision bare-metal hosts by k8 cluster. Although the bare-metal-operator and ironic.
I took the baremetal-operator form github repo and followed the steps in 
https://github.com/metal3-io/baremetal-operator/blob/master/docs/deploying.md. The baremetal-operator and ironic are both running fine. 
![image](https://user-images.githubusercontent.com/8111839/88288304-337a1b80-cd11-11ea-875f-ad16321a3a96.png)

However, when I try to apply BMH as given below.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-secret-1
type: Opaque
data:
  username: <my_root_suer>
  password: <my_rootPassword>

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh1
spec:
  online: true
  bmc:
    address: <ip_Address>
    credentialsName: bmc-secret-1
    disableCertificateVerification: true
```

I am getting below error while **kubectl get bmh -n metal3**
error: no kind "BareMetalHost" is registered for version "metal3.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

Env details:
CentOs 7
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
> kubectl api-version | grep metal3
metal3.io/v1alpha1
```

Any help? anyone?
