### ISSUE TITLE
externally provisioned hosts without image settings should not expose ironic's error message

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#608]
If someone creates an externally provisioned host by hand, without the image information, like this:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: ostestv4-extra-worker-0-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ostestv4-extra-worker-0
spec:
  online: true
  bootMACAddress: 00:5a:ee:de:c3:1f
  bmc:
    address: redfish+http://192.168.111.1:8000/redfish/v1/Systems/6571b7f1-c279-4c72-a9ab-9a01e28b0628
    credentialsName: ostestv4-extra-worker-0-bmc-secret
  externallyProvisioned: true
```

the host enters an error state with this message:

```
Host adoption failed: Error while attempting to adopt node 08c5d7d8-8da3-4450-b026-809d189b8a5e: 
Cannot validate image information for node 08c5d7d8-8da3-4450-b026-809d189b8a5e because one or 
more parameters are missing from its instance_info and insufficent information is present to boot 
from a remote volume. Missing are: ['image_source', 'kernel', 'ramdisk'].
```

We should wait for the host to have all of the details it needs before registering it with Ironic.
