### ISSUE TITLE
Airship RAID requirements

### ISSUE THREAD

**Issue by MahnoorAsghar** [metal3-io/baremetal-operator#895]
## Introduction

As per @furkatgofurov7's suggestion in the community meeting, this issue is created to track the Airship requirements for performing RAID configuration via Metal3 (and Ironic). The user can specify the RAID controller names and their associated disks, along with the required RAID level, the desired number of disks and the amount of storage required. A related demo was presented last year. Here is a reference to the patch set: [Add RAID to example hardwareprofile](https://review.opendev.org/c/airship/airshipctl/+/749043)

## Previous work
* [PR 148](https://github.com/metal3-io/metal3-docs/pull/148/files) was created in the Metal3 docs for specifying the RAID configuration for a bare metal host via Metal3.
* [Issue 206](https://github.com/metal3-io/baremetal-operator/issues/206) contains relevant work done in metal3 to support RAID configuration in bare metal servers, using the Fujitsu iRMC driver.
* [PR 292](https://github.com/metal3-io/baremetal-operator/pull/292) in the BMO repository develops support for RAID config for bare metal servers.
* In terms of the CRD, the current implementation of the RAID has the following sections in it, for hardware RAID:
```yaml
spec:
  raid:
    hardwareRAIDVolumes:
      - sizeGibiBytes: 1000
        level: 1
        name: volume-name
        rotational: true
        numberOfPhysicalDisks: 2
```
We propose to add fields into the CRD, in the following manner. Note the generic disk identifiers used.

```yaml
spec:
  raid:
    hardwareRAIDVolumes:
      - sizeGibiBytes: 1000
        level: 1
        name: volume-1
        rotational: true
        numberOfPhysicalDisks: 2
        physicalDisks:
          - diskName: Disk-1
          - diskName: Disk-2
        controller: primary-controller
      - sizeGibiBytes: 2000
        level: 0
        name: volume-2
        rotational: false
        numberOfPhysicalDisks: 2
        physicalDisks:
          - diskName: Disk-3
          - diskName: Disk-4
        controller: secondary-controller-2
```

## Possible Issues and Proposed Solutions
* **Disk name and RAID controller name generation** 
**Issue:** Redfish requires the explicit RAID controller and disk names in order to do the RAID configuration, but it would be more convenient if the user did not have to know the low level details of their system (i.e. vendor specific naming)
Here is the Redfish Action URI: ``{Base URI of target resource}/Actions/Volume.ChangeRAIDLayout``
(Provided in Section 6.109.4.2 of [this link](https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2021.1.pdf))
**Solution:** The disk names can be generated using the Redfish logic constructing a human friendly identifier or label for hardware devices. [Linked here](https://github.com/DMTF/Redfish-Tacklebox/blob/e429f70a79cfe288756618498ce485ab4be37131/redfish_utilities/inventory.py#L192)

* **Existing disk selection logic**
**Issue:** Since the user specifies generic disk names, they need to be mapped to vendor-specific names before requesting the RAID config. 
**Solution:** Disk selection logic needs to be implemented in the most appropriate place. It can be implemented in the respective Ironic drivers. Ironic requires a vendor independent implementation for this purpose. Airship may require that the user be unaware of the storage subsystem details when requesting the RAID config. 

## Possible Approaches
* One possible solution is to let the user specify the required disks and RAID controller needed. If it is available, the RAID configuration can be applied. If not, the BMO can present an error.
* Airship can perform inventory of the storage subsystems available in the cluster, so the user can construct a RAID configuration accordingly. Conversely, the logic to select the physical disks and associated controllers may be implemented in Airship, whilst the user just specifies the high level requirements.

We would like some feedback from the metal3 community for the problems, proposed solutions and approaches given above.
