### ISSUE TITLE
What's the difference of ironic-log-watch and ironic-inspector-log-watch container in the ironic pod?

### ISSUE THREAD

**Issue by nkwangleiGIT** [metal3-io/baremetal-operator#931]
A I can see, we have two containers in the ironic pod named ironic-log-watch and ironic-inspector-log-watch. They have the same entrypoint command, so I think they're duplicated containers to check the log in the /shared directory.
Do we need to remove the ironic-inspector-log-watch container in the deployment file?

```
  - command:
    - /bin/runlogwatch.sh
    image: quay.io/metal3-io/ironic
    imagePullPolicy: Always
    name: ironic-log-watch
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /shared
      name: ironic-data-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4zhjh
      readOnly: true
  - command:
    - /bin/runlogwatch.sh
    image: quay.io/metal3-io/ironic
    imagePullPolicy: Always
    name: ironic-inspector-log-watch
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /shared
      name: ironic-data-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4zhjh
      readOnly: true
```
